language: cpp
dist: bionic

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - cd docs
  - doxygen doxygen.conf
  - wget https://madour.github.io/projects/NasNas/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: docs
  repo: Madour/NasNas
