language: cpp

branches:
  only:
    - master

sudo: enabled

before_install:
  - sudo apt-get update
  - sudo apt-get install -y doxygen

script:
  - cd docs
  - doxygen doxygen.conf

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: docs/html
  repo: Madour/NasNas
  target-branch: master
