language: cpp

branches:
  only:
    - master

sudo: enabled

before_install:
  - sudo apt-get update
  - sudo apt-get install -y doxygen

script:
  - cd docs
  - doxygen doxygen.conf

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: docs
  repo: Madour/NasNas
