set(NasNas_Src "")
set(NasNas_Inc "")
if (NOT NASNAS_PATH)
    set(NASNAS_PATH ".")
endif()

add_definitions(-DNS_DATA)
include(${NASNAS_PATH}/cmake/Data.cmake)

add_definitions(-DNS_CORE)
include(${NASNAS_PATH}/cmake/Core.cmake)

if(NASNAS_BUILD_RESLIB)
    message(STATUS "NasNas : Will build \"reslib\" module")
    add_definitions(-DNS_RESLIB)
    include(${NASNAS_PATH}/cmake/Reslib.cmake)
endif()

if(NASNAS_BUILD_ECS)
    message(STATUS "NasNas : Will build \"ecs\" module")
    add_definitions(-DNS_ECS)
    include(${NASNAS_PATH}/cmake/Ecs.cmake)
endif()

if(NASNAS_BUILD_TILEMAPPING)
    message(STATUS "NasNas : Will build \"tilemapping\" module")
    add_definitions(-DNS_TILEMAPPING)
    include(${NASNAS_PATH}/cmake/Tilemapping.cmake)
endif()

if(NASNAS_BUILD_UI)
    message(STATUS "NasNas : Will build \"ui\" module")
    add_definitions(-DNS_UI)
    include(${NASNAS_PATH}/cmake/Ui.cmake)
endif()